apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: voting
  labels:
    app.kubernetes.io/name: voting-app
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: voting-app
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP