apiVersion: v1
kind: ConfigMap
metadata:
  name: voting-config
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
data:
  OPTION_A: {{ .Values.app.optionA | quote }}
  OPTION_B: {{ .Values.app.optionB | quote }}
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  POSTGRES_HOST: {{ .Values.database.host | quote }}
  POSTGRES_PORT: {{ .Values.database.port | quote }}
  POSTGRES_DB: {{ .Values.database.name | quote }}
  POSTGRES_USER: {{ .Values.database.user | quote }}
  RESULT_PORT: {{ .Values.app.resultPort | quote }}
  APP_PORT: {{ .Values.app.port | quote }}
