{{- range $name, $config := dict "vote" .Values.hpa.vote "result" .Values.hpa.result }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}-hpa
  labels:
    {{- include "voting-app.labels" $ | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $name }}
  minReplicas: {{ $config.minReplicas }}
  maxReplicas: {{ $config.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $config.cpuUtilization }}
---
{{- end }}
