apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
  labels:
    app.kubernetes.io/name: voting-app
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: voting-app
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
