apiVersion: v1
kind: ConfigMap
metadata:
  name: voting-config
  namespace: voting
  labels:
    app.kubernetes.io/name: voting-app
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: voting-app
data:
  OPTION_A: "Cats"
  OPTION_B: "Dogs"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "voting-app-dev-postgres.c90g46smyke5.ap-south-1.rds.amazonaws.com"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  RESULT_PORT: "4000"
  APP_PORT: "80"