apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-helm-dev
  namespace: argocd
spec:
  project: voting-project
  source:
    repoURL: https://github.com/ADHITHYAAMARAGONDA/voting-app-devops.git
    targetRevision: main
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: voting
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true