name: Build and Push Vote

on:
  push:
    branches: [main]
    paths:
      - vote/**
      - .github/workflows/call-docker-build-vote.yaml
  pull_request:
    branches: [main]
    paths:
      - vote/**
      - .github/workflows/call-docker-build-vote.yaml

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        if: github.event_name == 'push'
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ap-south-1
      - uses: aws-actions/amazon-ecr-login@v2
        if: github.event_name == 'push'
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: ./vote
          push: ${{ github.event_name == 'push' }}
          platforms: linux/amd64
          tags: |
            841162701696.dkr.ecr.ap-south-1.amazonaws.com/voting-app/vote:${{ github.sha }}
            841162701696.dkr.ecr.ap-south-1.amazonaws.com/voting-app/vote:latest
